// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exchange.proto

package exchange.proto_out;

public interface CurrencyResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CurrencyResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Currency Results = 1;</code>
   */
  java.util.List<exchange.proto_out.Currency> 
      getResultsList();
  /**
   * <code>repeated .Currency Results = 1;</code>
   */
  exchange.proto_out.Currency getResults(int index);
  /**
   * <code>repeated .Currency Results = 1;</code>
   */
  int getResultsCount();
  /**
   * <code>repeated .Currency Results = 1;</code>
   */
  java.util.List<? extends exchange.proto_out.CurrencyOrBuilder> 
      getResultsOrBuilderList();
  /**
   * <code>repeated .Currency Results = 1;</code>
   */
  exchange.proto_out.CurrencyOrBuilder getResultsOrBuilder(
      int index);
}
