// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exchange.proto

package exchange.proto_out;

public interface CurrencyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Currency)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.CurrencyType Type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>.CurrencyType Type = 1;</code>
   */
  exchange.proto_out.CurrencyType getType();

  /**
   * <code>double Value = 2;</code>
   */
  double getValue();
}
