// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exchange.proto

package exchange.proto_out;

public final class CurrencyProto {
  private CurrencyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CurrencyArguments_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CurrencyArguments_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Currency_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Currency_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CurrencyResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CurrencyResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016exchange.proto\"`\n\021CurrencyArguments\022(\n" +
      "\021ReferenceCurrency\030\001 \001(\0162\r.CurrencyType\022" +
      "!\n\nCurrencies\030\002 \003(\0162\r.CurrencyType\"6\n\010Cu" +
      "rrency\022\033\n\004Type\030\001 \001(\0162\r.CurrencyType\022\r\n\005V" +
      "alue\030\002 \001(\001\",\n\016CurrencyResult\022\032\n\007Results\030" +
      "\001 \003(\0132\t.Currency*D\n\014CurrencyType\022\007\n\003PLN\020" +
      "\000\022\007\n\003EUR\020\001\022\007\n\003USD\020\002\022\007\n\003CHF\020\003\022\007\n\003GBP\020\004\022\007\n" +
      "\003JPY\020\0052G\n\020CurrencyExchange\0223\n\010GetValue\022\022" +
      ".CurrencyArguments\032\017.CurrencyResult\"\0000\001B" +
      "+\n\022exchange.proto_outB\rCurrencyProtoP\001\242\002" +
      "\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CurrencyArguments_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CurrencyArguments_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CurrencyArguments_descriptor,
        new java.lang.String[] { "ReferenceCurrency", "Currencies", });
    internal_static_Currency_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Currency_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Currency_descriptor,
        new java.lang.String[] { "Type", "Value", });
    internal_static_CurrencyResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CurrencyResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CurrencyResult_descriptor,
        new java.lang.String[] { "Results", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
