# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto_out import exchange_pb2 as exchange__pb2


class CurrencyExchangeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetValue = channel.unary_stream(
        '/CurrencyExchange/GetValue',
        request_serializer=exchange__pb2.CurrencyArguments.SerializeToString,
        response_deserializer=exchange__pb2.CurrencyResult.FromString,
        )


class CurrencyExchangeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetValue(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CurrencyExchangeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetValue': grpc.unary_stream_rpc_method_handler(
          servicer.GetValue,
          request_deserializer=exchange__pb2.CurrencyArguments.FromString,
          response_serializer=exchange__pb2.CurrencyResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CurrencyExchange', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
